-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 09:42:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beautycompany
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beautycompany
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beautycompany` DEFAULT CHARACTER SET utf8 ;
USE `beautycompany` ;

-- -----------------------------------------------------
-- Table `beautycompany`.`especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautycompany`.`especialista` (
  `nome_especialista` VARCHAR(50) NOT NULL,
  `cpf_especialista` VARCHAR(11) NOT NULL,
  `data_nascimento_especialista` DATE NULL,
  `endereco_especialista` VARCHAR(70) NULL,
  `email_especialista` VARCHAR(70) NULL,
  `genero_especialista` VARCHAR(12) NULL,
  `telefone_especialista` VARCHAR(11) NULL,
  `formacao_especialista` VARCHAR(500) NULL,
  `experiencia_especialista` VARCHAR(500) NULL,
  `objetivo_especialista` VARCHAR(100) NULL,
  PRIMARY KEY (`cpf_especialista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautycompany`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautycompany`.`cliente` (
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NULL,
  `endereco` VARCHAR(70) NULL,
  `email` VARCHAR(70) NULL,
  `senha` VARCHAR(8) NULL,
  `is_admin` boolean default false,
  `telefone` VARCHAR(11) NULL,
  `genero` VARCHAR(12) NULL,
  `whatsapp` VARCHAR(12) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautycompany`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautycompany`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_pedido` FLOAT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `frete_pedido` FLOAT NULL,
  `data_pedido` DATE NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_cpf`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `beautycompany`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautycompany`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautycompany`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(50) NULL,
  `valor_produto` FLOAT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `beautycompany`.`pedido_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautycompany`.`pedido_has_produto` (
  `pedido_id_pedido` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`pedido_id_pedido`, `produto_id_produto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_id_produto`) ,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_id_pedido`) ,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `beautycompany`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `beautycompany`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;